In [3]:
import pandas as pd

In [4]:
info = pd.read_csv('./per-capita-co-emissions.csv')

# Analisis de datos Percapita CO2 Anual

In [ ]:
## Datos Iniciales

In [7]:
info

            Entity  Year  Annual CO₂ emissions (per capita)
0      Afghanistan  1949                           0.001992
1      Afghanistan  1950                           0.010837
2      Afghanistan  1951                           0.011625
3      Afghanistan  1952                           0.011468
4      Afghanistan  1953                           0.013123
...            ...   ...                                ...
26177     Zimbabwe  2019                           0.672040
26178     Zimbabwe  2020                           0.547085
26179     Zimbabwe  2021                           0.645915
26180     Zimbabwe  2022                           0.648761
26181     Zimbabwe  2023                           0.683201

[26182 rows x 3 columns]

### Nombre de columnas

In [8]:
info.columns

Index(['Entity', 'Year', 'Annual CO₂ emissions (per capita)'], dtype='object')

### Lista de paises

In [9]:
info['Entity'].unique()

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Asia', 'Asia (excl. China and India)', 'Australia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
       'Bolivia', 'Bonaire Sint Eustatius and Saba',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czechia',
       'Democratic Republic of Congo', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Europe', 'Europe (excl. EU-27)',
       'Europe (excl. EU-28)', 'European Union (27)',
       'European Union (28)', 'Faroe Islands', 'Fiji', 'Finland',
       'France', 'French Polynesia', 'Gabon', 'Gambia', 'Georgia',
       'Germany', 'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'High-income countries', 'Honduras', 'Hong Kong', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos',
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Low-income countries',
       'Lower-middle-income countries', 'Luxembourg', 'Macao',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Mongolia', 'Montenegro',
       'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North America',
       'North America (excl. USA)', 'North Korea', 'North Macedonia',
       'Norway', 'Oceania', 'Oman', 'Pakistan', 'Palau', 'Palestine',
       'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South America',
       'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Upper-middle-income countries', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela', 'Vietnam', 'Wallis and Futuna', 'World',
       'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

## Analisamos de datos CO2 per capita con mayor y menor emision

In [11]:
ultimo_año = info['Year'].max()

In [12]:
info_ultimo = info[info['Year'] == ultimo_año]

In [14]:
mayor = info_ultimo['Annual CO₂ emissions (per capita)'].max()
info_ultimo[info_ultimo['Annual CO₂ emissions (per capita)'] == mayor]

      Entity  Year  Annual CO₂ emissions (per capita)
19554  Qatar  2023                          38.842007

In [15]:
menor = info_ultimo['Annual CO₂ emissions (per capita)'].min()
info_ultimo[info_ultimo['Annual CO₂ emissions (per capita)'] == menor]

        Entity  Year  Annual CO₂ emissions (per capita)
21465  Somalia  2023                           0.030373

### Agrupamos los paises con minimo y maximo historicos

In [17]:
maximos = info.groupby('Entity')['Annual CO₂ emissions (per capita)'].max().sort_values(ascending=False)
maximos.head(20)

Entity
Sint Maarten (Dutch part)          796.390800
Kuwait                             364.699400
Brunei                             245.081000
Qatar                              121.810740
Curacao                            117.922554
United Arab Emirates                85.580185
Bahamas                             44.306828
Luxembourg                          41.049470
Bahrain                             39.740930
Trinidad and Tobago                 33.976368
Aruba                               29.220015
Saudi Arabia                        27.983114
Estonia                             25.456888
Bonaire Sint Eustatius and Saba     24.795895
United States                       22.257160
New Caledonia                       21.888735
Antigua and Barbuda                 19.702631
Australia                           19.113388
Oman                                18.560102
Nauru                               18.477478
Name: Annual CO₂ emissions (per capita), dtype: float64

In [19]:
minimo = info.groupby('Entity')['Annual CO₂ emissions (per capita)'].min().sort_values()
minimo.head(20)

Entity
El Salvador                     0.0
Kosovo                          0.0
Kuwait                          0.0
Nicaragua                       0.0
Norway                          0.0
Iraq                            0.0
New Zealand                     0.0
Oceania                         0.0
Ecuador                         0.0
Paraguay                        0.0
Saudi Arabia                    0.0
Senegal                         0.0
Europe (excl. EU-28)            0.0
Honduras                        0.0
Haiti                           0.0
Taiwan                          0.0
Guatemala                       0.0
Australia                       0.0
Asia (excl. China and India)    0.0
East Timor                      0.0
Name: Annual CO₂ emissions (per capita), dtype: float64

## Visualizacion con grafico de barra de 5 paises