<h3>Proyecto 1</h3>
<h1>Student Performance in Exams</h1>
<p>Este conjunto de datos contiene información sobre el rendimiento de distintos estudiantes en tres exámenes y algunas características demográficas.</p>
<h3>El conjunto tiene las siguientes columnas:</h3>
<ul>
<li><strong>Gender:</strong>
Indica el género del estudiante (hombre o mujer)</li>
<br>
<li><strong>Race/Ethnicity:</strong>
Agrupa a los estudiantes en cinco categorías</li><br>
<li><strong>Parental level of education:</strong>
Muesta el nivel educativo más alto alcanzado por los padres del estudiante</li><br>
<li><strong>Some High School:</strong>
Significa que el padre/madre asistió a la secundaria pero no la terminó.</li><br>
<li><strong>High School:</strong> 
Terminaron la secundaria pero no continuaron con sus estudios</li><br>
<li><strong>some college: </strong>
Asistieron a la universidad o una institución de educación superior, pero no la completo</li><br>
<li><strong>Aassociate Degree: </strong>
Es un título técnico o universitario de dos años (común en EE.UU.)</li><br>
<li><strong>Bachelor Degree:</strong>
Alguno de los padres obtuvo un título universitario</li><br>
<li><strong>Master Degree:</strong> 
Alguno de los títulos obtuvo un título de posgrado (máster o maestría)</li><br>
<li><strong>Lunch:</strong>
Indica el tipo de almuerzo que recibe el estudiante</li><br>
<li><strong>Standard:</strong> 
Almuerzo de pago estándar</li><br>
<li><strong>Free/Reduced:</strong> 
Almuerzo gratuito o con descuento</li><br>
<li><strong>Test Preparation Course:</strong>
Indica si el estudiante completó un curso de preparación antes del examen</li><br>
<li><strong>Math Score:</strong>
Puntaje obtenido por el estudiante en matemáticas</li><br>
<li><strong>Reading Score:</strong>
Puntaje obtenido por el estudiante en lectura</li><br>
<li><strong>Writing Score:</strong>
Puntaje obtenido por el estudiante en escritura</li><br>
</ul>

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('../python/practica/project/StudentsPerformance.csv')

In [4]:
data.head() # revisamos  que este cargado el dataset

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
data.shape # revisamos las dimensiones del dataset

(1000, 8)

In [6]:
data.info() # revisamos la informacion del dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [7]:
data.describe() # obtenemos un resumen estadístico de los datos

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [8]:
data.isnull().sum() # verificamos si hay valores nulos en el dataset

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [9]:
data.columns # obtenemos los nombres de las columnas

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [10]:
data[['math score', 'reading score', 'writing score']].agg(['mean', 'median' ,'std']) # obtenemos estadisticas descriptivas de las columnas de puntajes

        math score  reading score  writing score
mean      66.08900      69.169000      68.054000
median    66.00000      70.000000      69.000000
std       15.16308      14.600192      15.195657

<h3> Cantidad de alumnos por genero</h3>

In [11]:
data['gender'].value_counts() # contamos la cantidad de alumnos por genero

gender
female    518
male      482
Name: count, dtype: int64

<h3> Cantidad de alumnos  segun el nivel educativo de los padres</h3>

In [12]:
data['parental level of education'].value_counts() # contamos la cantidad de alumnos por nivel educativo de los padres

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

<h3>Cantidad de alumnos segun tipo de almuerzo </h3>

In [13]:
data['lunch'].value_counts() # contamos la cantidad de alumnos por tipo de almuerzo

lunch
standard        645
free/reduced    355
Name: count, dtype: int64

<h3>Alumnos por genero, nivel educativo de los padres y almuerzo</h3>

In [14]:
data[['gender', 'parental level of education', 'lunch']].value_counts() # contamos la cantidad de alumnos por genero, nivel educativo de los padres y tipo de almuerzo

gender  parental level of education  lunch
female  associate's degree           standard        80
        some college                 standard        74
male    some college                 standard        73
        high school                  standard        69
        associate's degree           standard        65
        some high school             standard        63
female  high school                  standard        57
        some high school             standard        55
        some college                 free/reduced    44
male    associate's degree           free/reduced    41
female  bachelor's degree            standard        41
        high school                  free/reduced    37
        some high school             free/reduced    36
        associate's degree           free/reduced    36
male    some college                 free/reduced    35
        bachelor's degree            standard        33
        high school                  free/reduced    33
        some high school             free/reduced    25
female  master's degree              standard        22
male    bachelor's degree            free/reduced    22
female  bachelor's degree            free/reduced    22
        master's degree              free/reduced    14
male    master's degree              standard        13
                                     free/reduced    10
Name: count, dtype: int64

<h3>Agregando columna Promedio</h3>

In [15]:
data['promedio'] = data[['math score', 'reading score', 'writing score']].mean(axis=1).round(2) # creamos una nueva columna con el promedio de los puntajes

In [16]:
data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,promedio
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master's degree,standard,none,90,95,93,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33

<h5>Definiendo categoria_clasificacion </h5>

In [17]:
def categoria_calificacion(promedio):
    if promedio >= 90:
        return 'A'
    elif promedio >= 80:
        return 'B'
    elif promedio >= 70:
        return 'C'
    elif promedio >= 60:
        return 'D'
    else:
        return 'F'

<h5>Agregando columna categoria_clasificacion</h5>

In [18]:
data['categoria_promedio'] = data['promedio'].apply(categoria_calificacion) # creamos una nueva columna con la categoria de calificacion segun el promedio

In [19]:
data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,promedio,categoria_promedio
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67,C
1,female,group C,some college,standard,completed,69,90,88,82.33,B
2,female,group B,master's degree,standard,none,90,95,93,92.67,A
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33,F
4,male,group C,some college,standard,none,76,78,75,76.33,C

<h3>Clasificacion de alumnos por categoria</h3>

In [20]:
data['categoria_promedio'].value_counts() # contamos la cantidad de alumnos por categoria de calificacion

categoria_promedio
F    285
C    261
D    256
B    146
A     52
Name: count, dtype: int64

<h3>Correlacion entre puntajes</h3>

In [21]:
data[['math score', 'reading score', 'writing score']].corr() # obtenemos la correlacion entre los puntajes

               math score  reading score  writing score
math score       1.000000       0.817580       0.802642
reading score    0.817580       1.000000       0.954598
writing score    0.802642       0.954598       1.000000

<h3>Vemos lo siguientes casos:</h3>
<ul>
<li>En matematica vemos q tiene una mayor puntaje, q estaria afectando a los puntajes de  lectura con 0.81 y escritura con 0.80</li>
 <li>En Lectura vemos q el puntaje es mayor q matematica con 0.81 cosa q estaria afectando a esta materia pero no asi a la materia de escritura con 0.95 de puntaje de correlacion</li>
 <li>En escritura vamos a ver q cuando el puntaje es mayor q a matematica afecta a esta materia, pero no asi a la materia de lectura.</li>
 </ul>

<h3>Agrupacion de datos por genero con (.groupby)</h3>

In [ ]:
data.groupby('gender')[['math score', 'reading score', 'writing score']].mean() # obtenemos el promedio de los puntajes por genero

        math score  reading score  writing score
gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203

<h3>Al agrupar por genero:</h3>
<p>
 Se puede ver que las mujeres obtienen mejores promedios en Lectura y Escritura que los hombre.
 <br>Los hombres obtienen mejores promedios en Matematica que las mujeres.</p>

<h3>Agrupacion del nivel educativo de los padres</h3>

In [22]:
data.groupby('parental level of education')[['math score', 'reading score', 'writing score']].mean() # obtenemos el promedio de los puntajes por nivel educativo de los padres

                             math score  reading score  writing score
parental level of education
associate's degree            67.882883      70.927928      69.896396
bachelor's degree             69.389831      73.000000      73.381356
high school                   62.137755      64.704082      62.448980
master's degree               69.745763      75.372881      75.677966
some college                  67.128319      69.460177      68.840708
some high school              63.497207      66.938547      64.888268

<h3>Notamos que:</h3>
<ul>
<li>Los alumnos que tienen mejores notas en Matematica, Lectura y Escritura tienen padres con una maestria (master's degree)</li><br>
<li>Los alumnos que tienen notas bajas en Matematica, Lectura y Escritura tienen padres con escuela secundaria (High school)</li>
</ul>
<p>Basandonos en este conjunto de datos agrupados vemos que el nivel educativo de los padres si tiene relacion con la educacion de los hijos</p>

<h3>Agrupacion por almuerzo que reciben los estudiantes</h3>

In [23]:
data.groupby('lunch')[['math score', 'reading score', 'writing score']].mean() # obtenemos el promedio de los puntajes por tipo de almuerzo

              math score  reading score  writing score
lunch
free/reduced   58.921127      64.653521      63.022535
standard       70.034109      71.654264      70.823256

<p>Al finalizar este analisis se concluye que los estudiantes que obtuvieron los mejores promedios en Matematica, Lectura y Escritura tienden a ser aquellos, cuyos padres tienen un nivel educativo superior, como una maestria, y que ademas consumen almuerzos con mayor valor nutricional.<br>
Por otro lado, se observa que un buen desempeño en una materia puedo o no influir  de manera positiva en el rendimiento las demas, tanto en estudiantes hombres como en mujeres.
  </p>